apiVersion: v1
kind: Namespace
metadata:
  name: secure-apps # Namespace for the Project
  labels:
    policy-enforcement: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: logging # Namespace for logging
  labels:
    policy-enforcement: disabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: ai-report
  labels:
    policy-enforcement: enabled
    