apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-resource-limits
spec:
  validationFailureAction: Enforce
  rules:
    - name: check-resource-limits
      match:
        any:
          - resources:
              kinds:
                - Pod
              namespaceSelector:
                matchLabels:
                  policy-enforcement: enabled
      validate:
        message: >-
          VIOLATION: CPU and memory limits required.
          Container must define resources.limits.cpu (max 2 core)
          and resources.limits.memory (max 5Gi).
        pattern:
          spec:
            containers:
              - resources:
                  limits:
                    cpu: "?*"
                    memory: "?*"
